// <auto-generated />
using System;
using Isdocovac.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Isdocovac.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260117231243_AddFakturoidOAuthState")]
    partial class AddFakturoidOAuthState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Isdocovac.Models.AuthenticationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("Email", "ExpiresAt");

                    b.ToTable("authentication_tokens", (string)null);
                });

            modelBuilder.Entity("Isdocovac.Models.FakturoidConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("AccessTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AccountName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AccountSlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountSlug");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("fakturoid_connections", (string)null);
                });

            modelBuilder.Entity("Isdocovac.Models.FakturoidInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BankAccount")
                        .HasColumnType("text");

                    b.Property<int?>("BankAccountId")
                        .HasColumnType("integer");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClientCity")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ClientCountry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientDeliveryCity")
                        .HasColumnType("text");

                    b.Property<string>("ClientDeliveryCountry")
                        .HasColumnType("text");

                    b.Property<string>("ClientDeliveryName")
                        .HasColumnType("text");

                    b.Property<string>("ClientDeliveryStreet")
                        .HasColumnType("text");

                    b.Property<string>("ClientDeliveryZip")
                        .HasColumnType("text");

                    b.Property<bool>("ClientHasDeliveryAddress")
                        .HasColumnType("boolean");

                    b.Property<string>("ClientLocalVatNo")
                        .HasColumnType("text");

                    b.Property<string>("ClientName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ClientRegistrationNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientStreet")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ClientVatNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientZip")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ConstantSymbol")
                        .HasColumnType("text");

                    b.Property<int?>("CorrectionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CustomId")
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Due")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DueOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ExchangeRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid>("FakturoidConnectionId")
                        .HasColumnType("uuid");

                    b.Property<int>("FakturoidId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FakturoidUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FooterNote")
                        .HasColumnType("text");

                    b.Property<int?>("GeneratorId")
                        .HasColumnType("integer");

                    b.Property<string>("Gopay")
                        .HasColumnType("text");

                    b.Property<string>("HtmlUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Iban")
                        .HasColumnType("text");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IssuedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("NativeRemainingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NativeSubtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NativeTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NativeVatRatesSummary")
                        .HasColumnType("jsonb");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("NumberFormatId")
                        .HasColumnType("integer");

                    b.Property<bool>("Open")
                        .HasColumnType("boolean");

                    b.Property<bool>("Overdue")
                        .HasColumnType("boolean");

                    b.Property<bool>("Paid")
                        .HasColumnType("boolean");

                    b.Property<string>("PaidAdvances")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("PaidOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Paypal")
                        .HasColumnType("text");

                    b.Property<string>("PrivateNote")
                        .HasColumnType("text");

                    b.Property<string>("ProformaFollowupDocument")
                        .HasColumnType("text");

                    b.Property<string>("PublicHtmlUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("RelatedId")
                        .HasColumnType("integer");

                    b.Property<decimal>("RemainingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Sent")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpecificSymbol")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubjectCustomId")
                        .HasColumnType("text");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SwiftBic")
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .HasColumnType("jsonb");

                    b.Property<string>("Token")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Uncollectible")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UncollectibleAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VariableSymbol")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VatPriceMode")
                        .HasColumnType("text");

                    b.Property<string>("VatRatesSummary")
                        .HasColumnType("jsonb");

                    b.Property<string>("YourCity")
                        .HasColumnType("text");

                    b.Property<string>("YourCountry")
                        .HasColumnType("text");

                    b.Property<string>("YourLocalVatNo")
                        .HasColumnType("text");

                    b.Property<string>("YourName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("YourRegistrationNo")
                        .HasColumnType("text");

                    b.Property<string>("YourStreet")
                        .HasColumnType("text");

                    b.Property<string>("YourVatNo")
                        .HasColumnType("text");

                    b.Property<string>("YourZip")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DueOn");

                    b.HasIndex("FakturoidConnectionId");

                    b.HasIndex("FakturoidId");

                    b.HasIndex("IssuedOn");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("FakturoidConnectionId", "FakturoidId")
                        .IsUnique();

                    b.HasIndex("FakturoidConnectionId", "LastSyncedAt");

                    b.ToTable("fakturoid_invoices", (string)null);
                });

            modelBuilder.Entity("Isdocovac.Models.FakturoidInvoiceAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("FakturoidInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FakturoidInvoiceId");

                    b.ToTable("fakturoid_invoice_attachments", (string)null);
                });

            modelBuilder.Entity("Isdocovac.Models.FakturoidInvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FakturoidInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<int?>("InventoryItemId")
                        .HasColumnType("integer");

                    b.Property<int>("LineOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("TotalPriceWithVat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPriceWithoutVat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalVat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPriceWithVat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPriceWithoutVat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VatRate")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("FakturoidInvoiceId");

                    b.HasIndex("FakturoidInvoiceId", "LineOrder");

                    b.ToTable("fakturoid_invoice_lines", (string)null);
                });

            modelBuilder.Entity("Isdocovac.Models.FakturoidInvoicePayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BankAccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("FakturoidInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<int>("FakturoidPaymentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("NativeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaidOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TaxDocumentId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VariableSymbol")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("FakturoidInvoiceId");

                    b.HasIndex("FakturoidPaymentId");

                    b.HasIndex("PaidOn");

                    b.HasIndex("FakturoidInvoiceId", "FakturoidPaymentId")
                        .IsUnique();

                    b.ToTable("fakturoid_invoice_payments", (string)null);
                });

            modelBuilder.Entity("Isdocovac.Models.FakturoidOAuthState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StateHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId", "StateHash")
                        .IsUnique();

                    b.ToTable("fakturoid_oauth_states", (string)null);
                });

            modelBuilder.Entity("Isdocovac.Models.InvoiceProcessing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("InvoiceUploadId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParsedIsdocId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceUploadId");

                    b.HasIndex("ParsedIsdocId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("invoice_processings", (string)null);
                });

            modelBuilder.Entity("Isdocovac.Models.InvoiceUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlobContainerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("BlobUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UploadedAt");

                    b.HasIndex("UserId");

                    b.ToTable("invoice_uploads", (string)null);
                });

            modelBuilder.Entity("Isdocovac.Models.LoginAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<bool>("WasSuccessful")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Email", "AttemptedAt");

                    b.HasIndex("IpAddress", "AttemptedAt");

                    b.ToTable("login_attempts", (string)null);
                });

            modelBuilder.Entity("Isdocovac.Models.ParsedIsdoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("InvoiceUploadId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ParsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParsedData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ValidationErrors")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceUploadId");

                    b.HasIndex("ParsedAt");

                    b.ToTable("parsed_isdocs", (string)null);
                });

            modelBuilder.Entity("Isdocovac.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Isdocovac.Models.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionTokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("SessionTokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("Isdocovac.Models.FakturoidConnection", b =>
                {
                    b.HasOne("Isdocovac.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Isdocovac.Models.FakturoidInvoice", b =>
                {
                    b.HasOne("Isdocovac.Models.FakturoidConnection", "Connection")
                        .WithMany("Invoices")
                        .HasForeignKey("FakturoidConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("Isdocovac.Models.FakturoidInvoiceAttachment", b =>
                {
                    b.HasOne("Isdocovac.Models.FakturoidInvoice", "Invoice")
                        .WithMany("Attachments")
                        .HasForeignKey("FakturoidInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Isdocovac.Models.FakturoidInvoiceLine", b =>
                {
                    b.HasOne("Isdocovac.Models.FakturoidInvoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("FakturoidInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Isdocovac.Models.FakturoidInvoicePayment", b =>
                {
                    b.HasOne("Isdocovac.Models.FakturoidInvoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("FakturoidInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Isdocovac.Models.FakturoidOAuthState", b =>
                {
                    b.HasOne("Isdocovac.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Isdocovac.Models.InvoiceProcessing", b =>
                {
                    b.HasOne("Isdocovac.Models.InvoiceUpload", "InvoiceUpload")
                        .WithMany("Processings")
                        .HasForeignKey("InvoiceUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Isdocovac.Models.ParsedIsdoc", "ParsedIsdoc")
                        .WithMany()
                        .HasForeignKey("ParsedIsdocId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("InvoiceUpload");

                    b.Navigation("ParsedIsdoc");
                });

            modelBuilder.Entity("Isdocovac.Models.InvoiceUpload", b =>
                {
                    b.HasOne("Isdocovac.Models.User", "User")
                        .WithMany("InvoiceUploads")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Isdocovac.Models.ParsedIsdoc", b =>
                {
                    b.HasOne("Isdocovac.Models.InvoiceUpload", "InvoiceUpload")
                        .WithMany("ParsedIsdocs")
                        .HasForeignKey("InvoiceUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvoiceUpload");
                });

            modelBuilder.Entity("Isdocovac.Models.UserSession", b =>
                {
                    b.HasOne("Isdocovac.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Isdocovac.Models.FakturoidConnection", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Isdocovac.Models.FakturoidInvoice", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Lines");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Isdocovac.Models.InvoiceUpload", b =>
                {
                    b.Navigation("ParsedIsdocs");

                    b.Navigation("Processings");
                });

            modelBuilder.Entity("Isdocovac.Models.User", b =>
                {
                    b.Navigation("InvoiceUploads");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
